---
- name: In-Memory inventory playbook
  hosts: workstation
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: openstack
      register: result

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"

    - debug:
        msg: "{{ groups }}"
        
    - name: test apps
      hosts: apps
        - debug: "apps group done"

    - name: test frontends
      hosts: frontends
        - debug: "frontends group done"

    - name: test appdbs
      hosts: appdbs
        - debug: "appdbs group done"
